MealSaver2.0/Pages/Canteen/CanteenMealPackages.cshtml.cs
using Domain;
using DomainServices.Repositories;
using DomainServices.Services.Interface;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MealSaver2._0.Pages.Canteen;

public class CanteenMealPackagesModel(IMealPackageRepository mealPackageRepository, ICanteenService canteenService, IUserService userService) : PageModel
{
    public IQueryable<Domain.MealPackage> MealPackages { get; set; }
    
    [BindProperty]
    
    public string Message { get; set; }
    
    public async Task<IActionResult> OnGet()
    {
        Message = TempData["message"]?.ToString();
        return await OnGetCurrentCanteenPackages();
    }

    public async Task<IActionResult> OnGetCurrentCanteenPackages()
    {
        MealPackages = mealPackageRepository.GetAllCanteenPackages(userService.GetLoggedInUserInfo(User).Result as CanteenEmployee).OrderBy(m => m.PickupTimeTill);
        return Page();
    }

    public async Task<IActionResult> OnGetAllCanteenPackages()
    {
        MealPackages = mealPackageRepository.GetAllMealPackages().OrderBy(m => m.PickupTimeTill);;
        return Page();
    }

    public async Task<IActionResult> OnGetDeleteMealPackage(Guid id)
    {
        Message = await canteenService.DeleteMealPackage(id) switch
        {
            "success" => "Meal package deleted successfully",
            "not-found" => "Meal package not found",
            "already-reserved" => "Meal package has a reservation and cannot be deleted",
            _ => "Something went wrong"
        };
        TempData["message"] = Message;
        return RedirectToPage("/Canteen/CanteenMealPackages");
    }

    public async Task<IActionResult> OnGetEditMealPackage(Guid id)
    {
        if (mealPackageRepository.GetMealPackageById(id).ReservedById == null)
            return RedirectToPage("/Canteen/EditMealPackage", new { id });
        Message = "Meal package has a reservation and cannot be edited";
        TempData["message"] = Message;
        return RedirectToPage("/Canteen/CanteenMealPackages");
    }
}

MealSaver2.0/Pages/Canteen/CreateMealPackage.cshtml.cs
using Domain;
using DomainServices.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MealSaver2._0.Pages.Canteen;

public class CreateMealPackageModel(IProductRepository productRepository) : PageModel
{
    [BindProperty]
    public Domain.MealPackage MealPackage { get; set; }
    
    public IQueryable<Product> Products { get; set; }
    
    public void OnGet()
    {
        MealPackage = new Domain.MealPackage();
        Products = productRepository.GetAllProducts();
    }
    
    public IActionResult OnPost()
    {
        Products = productRepository.GetAllProducts();
        if (!ModelState.IsValid)
        {
            return Page();
        }
        
        return RedirectToPage("Index");
    }
}

MealSaver2.0/Pages/Canteen/EditMealPackage.cshtml.cs
using Domain;
using DomainServices.Repositories;
using DomainServices.Services.Interface;
using MealSaver2._0.Pages.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MealSaver2._0.Pages.Canteen;

public class EditMealPackage(IMealPackageRepository mealPackageRepository, IProductRepository productRepository, ICanteenService canteenService) : PageModel
{
    [BindProperty]
    public MealPackageViewModel MealPackage { get; set; }
    public IQueryable<Product> Products { get; set; }
    
    public void OnGet(Guid id)
    {
        var mealPackage = mealPackageRepository.GetMealPackageById(id);
        Products = productRepository.GetAllProducts();
        MealPackage = new MealPackageViewModel
        {
            Id = mealPackage.Id,
            DescriptiveName = mealPackage.DescriptiveName,
            PickupTimeTill = mealPackage.PickupTimeTill,
            Price = mealPackage.Price,
            MealType = mealPackage.MealType,
            SelectedProducts = mealPackage.Products.Select(p => p.Id).ToList(),
            CanteenId = mealPackage.CanteenId
        };
    }

    public async Task<IActionResult> OnPostAsync()
    {
        Products = productRepository.GetAllProducts();

        var currentMealPackage = mealPackageRepository.GetMealPackageById(MealPackage.Id);
        
                
        if(MealPackage.PickupTimeTill < DateTime.Now)
        {
            ModelState.AddModelError("MealPackage.PickupTimeTill", "Pickup time must be in the future");
        }

        if (MealPackage.PickupTimeTill > DateTime.Now.AddDays(2))
        {
            ModelState.AddModelError("MealPackage.PickupTimeTill", "Pickup time must be within 2 days");
        }
        
        if(currentMealPackage.ReservedById != null)
        {
            ModelState.AddModelError("MealPackage.Id", "This meal package is already reserved");
        }

        if (!ModelState.IsValid) return Page();
        var mealPackage = new Domain.MealPackage
        {
            DescriptiveName = MealPackage.DescriptiveName,
            PickupTimeFrom = DateTime.Now,
            PickupTimeTill = MealPackage.PickupTimeTill,
            Products = null,
            Is18Plus = false,
            Price = MealPackage.Price,
            MealType = MealPackage.MealType,
            CanteenId = MealPackage.CanteenId.Value
        };
        
        
        if (!await canteenService.UpdateMealPackage(currentMealPackage.Id, mealPackage, MealPackage.SelectedProducts)) return Page();
        TempData["Message"] = "Meal package edited successfully";
        return RedirectToPage("/Canteen/CanteenMealPackages");
    }
}

MealSaver2.0/Pages/Canteen/CanteenMealPackages.cshtml
@page
@model MealSaver2._0.Pages.Canteen.CanteenMealPackagesModel

<div class="container mt-4">
    @if (!string.IsNullOrEmpty(Model.Message))
    {
        <div class="alert alert-info">
            @Model.Message
        </div>
    }
    <div class="d-flex justify-content-between mb-3">
        <a asp-page="CreateMealPackage" class="btn secondary-color text-white">Create Meal Package</a>
        <a asp-page-handler="CurrentCanteenPackages" class="btn secondary-color text-white">View My Canteen Meal Packages</a>
        <a asp-page-handler="AllCanteenPackages" class="btn secondary-color text-white">View All Meal Packages</a>
    </div>

    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Product Amount</th>
            <th scope="col">Status</th>
            <th scope="col">Date</th>
            <th scope="col">Location</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var p in Model.MealPackages)
        {
            <tr>
                <td>@p.DescriptiveName</td>
                <td>@p.Products.Count</td>
                <td>@(p.ReservedById == null ? "Available" : "Reserved")</td>
                <td>@p.PickupTimeTill</td>
                <td>@p.Canteen.City, @p.Canteen.Location</td>
                <td>
                    <a asp-page-handler="EditMealPackage" asp-route-id="@p.Id" class="btn btn-sm btn-warning">Edit</a>
                    <a asp-page-handler="DeleteMealPackage" asp-route-id="@p.Id" class="btn btn-sm btn-danger">Delete</a>
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>

MealSaver2.0/Pages/Canteen/CreateMealPackage.cshtml
@page
@using Domain.Enums
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model MealSaver2._0.Pages.Canteen.CreateMealPackageModel
@{
    ViewData["Title"] = "Create Meal Package";
}

<div class="container mt-5">
    <form method="post" class="needs-validation" novalidate>
        <div class="mb-3">
            <label asp-for="MealPackage.DescriptiveName" class="form-label">Descriptive Name</label>
            <input asp-for="MealPackage.DescriptiveName" class="form-control" required />
            <span asp-validation-for="MealPackage.DescriptiveName" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label class="form-label">Products</label>
            <select asp-for="MealPackage.Products" class="form-control" multiple="multiple">
                @foreach (var product in Model.Products)
                {
                <option value="@product">@product.DescriptiveName</option>
                }
            </select>
            <span asp-validation-for="MealPackage.Products" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="MealPackage.PickupTimeTill" class="form-label">Pickup Time Till</label>
            <input asp-for="MealPackage.PickupTimeTill" type="datetime-local" class="form-control" min="@DateTime.Now.ToString("yyyy-MM-ddTHH:mm")" max="@DateTime.Now.AddDays(2).ToString("yyyy-MM-ddTHH:mm")" required />
            <span asp-validation-for="MealPackage.PickupTimeTill" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <div class="form-check">
                <input asp-for="MealPackage.Is18Plus" class="form-check-input" type="checkbox" />
                <label asp-for="MealPackage.Is18Plus" class="form-check-label">18+ Check</label>
            </div>
            <span asp-validation-for="MealPackage.Is18Plus" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="MealPackage.Price" class="form-label">Price</label>
            <input asp-for="MealPackage.Price" type="number" step="0.01" class="form-control" required />
            <span asp-validation-for="MealPackage.Price" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="MealPackage.MealType" class="form-label">Meal Type</label>
            <select asp-for="MealPackage.MealType" class="form-select">
                <option value="">Select Meal Type</option>
                @foreach (var type in Enum.GetValues(typeof(MealType)))
                {
                <option value="@type">@type</option>
                }
            </select>
            <span asp-validation-for="MealPackage.MealType" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary">Create Meal Package</button>
    </form>
</div>

MealSaver2.0/Pages/Canteen/EditMealPackage.cshtml
@page
@using Domain.Enums
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model MealSaver2._0.Pages.Canteen.EditMealPackage
@{
ViewData["Title"] = "Edit Meal Package";
}

<div class="container mt-5">
    <form method="post" class="needs-validation">
        <input asp-for="MealPackage.Id" type="hidden" value="@Model.MealPackage.Id"/>
        <span asp-validation-for="MealPackage.Id" class="text-danger"></span>
        <input asp-for="MealPackage.CanteenId" type="hidden" value="@Model.MealPackage.CanteenId"/>
        
        <div class="mb-3">
            <label asp-for="MealPackage.DescriptiveName" class="form-label">Descriptive Name</label>
            <input asp-for="MealPackage.DescriptiveName" class="form-control"/>
            <span asp-validation-for="MealPackage.DescriptiveName" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label class="form-label">Products</label>
            <select asp-for="MealPackage.SelectedProducts" class="form-control" multiple="multiple">
                @foreach (var product in Model.Products)
                {
                    <option value="@product.Id">@product.DescriptiveName</option>
                }
            </select>
            <span asp-validation-for="MealPackage.SelectedProducts" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="MealPackage.PickupTimeTill" class="form-label">Pickup Time Till</label>
            <input asp-for="MealPackage.PickupTimeTill" type="datetime-local" class="form-control"/>
            <span asp-validation-for="MealPackage.PickupTimeTill" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="MealPackage.Price" class="form-label">Price</label>
            <input asp-for="MealPackage.Price" type="number" step="0.01" class="form-control"/>
            <span asp-validation-for="MealPackage.Price" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="MealPackage.MealType" class="form-label">Meal Type</label>
            <select asp-for="MealPackage.MealType" class="form-select">
                @foreach (var type in Enum.GetValues(typeof(MealType)))
                {
                    <option value="@type">@type</option>
                }
            </select>
            <span asp-validation-for="MealPackage.MealType" class="text-danger"></span>
        </div>

        <button type="submit" class="btn secondary-color text-white">Update Meal Package</button>
    </form>
</div>